# Generated by Django 3.1.7 on 2021-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_option',
            field=models.ManyToManyField(through='product.ProductOption', to='product.Option'),
        ),
    ]
