# Generated by Django 3.1.7 on 2021-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdescription',
            old_name='page',
            new_name='total_page',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_option',
            new_name='product_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations',
            field=models.ManyToManyField(related_name='_product_recommendations_+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
