# Generated by Django 3.1.7 on 2021-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210318_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='classification',
            field=models.CharField(default='classification', max_length=45, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_url',
            field=models.CharField(default='url', max_length=2000),
            preserve_default=False,
        ),
    ]
