# Generated by Django 3.1.7 on 2021-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210319_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='classification',
            field=models.CharField(max_length=45),
        ),
    ]
