# Generated by Django 3.1.7 on 2021-03-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210319_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('classification', 'name')},
        ),
    ]
