# Generated by Django 3.1.7 on 2021-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210319_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
