# Generated by Django 3.1.7 on 2021-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='detailed_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='detailed_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryaddress',
            unique_together={('user', 'address', 'postal_code', 'detailed_address')},
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together={('user', 'coupon')},
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupons',
        ),
        migrations.AlterModelTable(
            name='deliveryaddress',
            table='delivery_addresses',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usercoupon',
            table='user_coupons',
        ),
    ]
