# Generated by Django 3.1.7 on 2021-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
        ('user', '0003_user_user_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_sub_category',
            field=models.ManyToManyField(through='product.CouponSubCategory', to='product.SubCategory'),
        ),
    ]
