# Generated by Django 3.1.7 on 2021-03-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_name'),
        ('product', '0009_auto_20210320_1645'),
        ('order', '0002_auto_20210318_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productoption'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productoption'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product', 'order', 'product_option')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('product', 'user', 'product_option')},
        ),
    ]
