# Generated by Django 3.1.7 on 2021-03-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_name'),
        ('product', '0009_auto_20210320_1645'),
        ('order', '0004_auto_20210322_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'order', 'product_option')},
        ),
    ]
